// Index of gallery sections across the site, used by search.js.
// Each entry: name (display), page (target HTML), anchor (optional, target h2 id), category (badge label).

const GALLERY_SECTIONS = [
	// Breads
	{ name: 'Pineapple Buns', page: 'breads.html', anchor: 'pineapple-buns', category: 'Bread' },
	{ name: 'Coffee Buns', page: 'breads.html', anchor: 'coffee-buns', category: 'Bread' },
	{ name: 'Cream Cheese Buns', page: 'breads.html', anchor: 'cream-cheese-buns', category: 'Bread' },
	{ name: 'Mantou', page: 'breads.html', anchor: 'mantou', category: 'Bread' },

	// Cakes
	{ name: 'Favorites', page: 'cakes.html', anchor: 'favorites', category: 'Cake' },
	{ name: 'Floral Cakes', page: 'cakes.html', anchor: 'floral-cakes', category: 'Cake' },
	{ name: 'Fruit Cakes', page: 'cakes.html', anchor: 'fruit-cakes', category: 'Cake' },
	{ name: 'Lunchbox Cakes', page: 'cakes.html', anchor: 'lunchbox-cakes', category: 'Cake' },
	{ name: 'Cake Pops', page: 'cakes.html', anchor: 'cake-pop', category: 'Cake' },
	{ name: 'Strawberry Cakes', page: 'cakes.html', anchor: 'strawberry-cakes', category: 'Cake' },
	{ name: 'Chocolate Cakes', page: 'cakes.html', anchor: 'chocolate-cakes', category: 'Cake' },
	{ name: 'Macaron Cakes', page: 'cakes.html', anchor: 'macaron-cakes', category: 'Cake' },
	{ name: 'Shopkin Cakes', page: 'cakes.html', anchor: 'shopkin-cakes', category: 'Cake' },
	{ name: 'Crepe Cakes', page: 'cakes.html', anchor: 'crepe-cakes', category: 'Cake' },
	{ name: 'Custom Cakes', page: 'cakes.html', anchor: 'custom-cakes', category: 'Cake' },
	{ name: 'Cake Archive', page: 'cakes.html', anchor: 'archive', category: 'Cake' },

	// Themed treats
	{ name: 'Tropical Theme', page: 'themed_treats.html', anchor: 'tropical-theme', category: 'Themed' },
	{ name: 'Alice in Wonderland', page: 'themed_treats.html', anchor: 'alice-in-wonderland', category: 'Themed' },
	{ name: 'Ice Cream Theme', page: 'themed_treats.html', anchor: 'ice-cream-theme', category: 'Themed' },
	{ name: 'Chanel Theme', page: 'themed_treats.html', anchor: 'chanel-theme', category: 'Themed' },
	{ name: 'Baby Blue and Oreo', page: 'themed_treats.html', anchor: 'baby-blue-and-oreo', category: 'Themed' },
	{ name: 'Cats and Dogs', page: 'themed_treats.html', anchor: 'cats-and-dogs', category: 'Themed' },
	{ name: 'Linzer Cookies', page: 'themed_treats.html', anchor: 'linzer-cookies', category: 'Themed' },
	{ name: 'Baby Shower', page: 'themed_treats.html', anchor: 'baby-shower', category: 'Themed' },
	{ name: 'Ube and Black Sesame Walnut Mooncakes', page: 'themed_treats.html', anchor: 'ube-mooncakes', category: 'Themed' },
	{ name: 'Poppy and Ombre Theme', page: 'themed_treats.html', anchor: 'poppy-ombre-theme', category: 'Themed' },
	{ name: 'Snakes and Geckos', page: 'themed_treats.html', anchor: 'snakes-and-geckos', category: 'Themed' },
	{ name: 'Ocean and Mermaid Theme', page: 'themed_treats.html', anchor: 'ocean-mermaid-theme', category: 'Themed' },
	{ name: 'Pirate Themed Treats', page: 'themed_treats.html', anchor: 'pirate-themed-treats', category: 'Themed' },
	{ name: 'Assorted Cupcakes', page: 'themed_treats.html', anchor: 'assorted-cupcakes', category: 'Themed' },

	// Top-level gallery pages
	{ name: 'Macarons', page: 'macarons.html', category: 'Page' },
	{ name: 'Cupcakes', page: 'cupcakes.html', category: 'Page' },
	{ name: 'Sugar Cookies', page: 'sugar_cookies.html', category: 'Page' },
	{ name: 'Savory', page: 'savory.html', category: 'Page' },
	{ name: 'Recipes', page: 'recipes.html', category: 'Page' },
	{ name: 'About Me', page: 'about_me.html', category: 'Page' },

	// Individual savory dishes
	{ name: 'Galbi Tang', page: 'savory.html', anchor: 'savory-galbi-tang', category: 'Savory' },
	{ name: 'Korean Chicken Noodle Soup', page: 'savory.html', anchor: 'savory-korean-chicken-noodle-soup', category: 'Savory' },
	{ name: 'Galbi, Tom Yum & Bok Choy', page: 'savory.html', anchor: 'savory-galbi-tom-yum-bok-choy', category: 'Savory' },
	{ name: 'Steamed Fish & Congee', page: 'savory.html', anchor: 'savory-steamed-fish-congee', category: 'Savory' },
	{ name: 'Steamed Fish, Galbi Tang & Bok Choy', page: 'savory.html', anchor: 'savory-steamed-fish-galbi-tang', category: 'Savory' },
	{ name: 'Steamed Fish, Tom Yum & Bok Choy', page: 'savory.html', anchor: 'savory-steamed-fish-tom-yum', category: 'Savory' },
	{ name: 'Steamed Fish, Tomato Egg & Pickled Fish Soup', page: 'savory.html', anchor: 'savory-steamed-fish-tomato-egg', category: 'Savory' },
	{ name: 'Pickled Cabbage Fish Soup', page: 'savory.html', anchor: 'savory-pickled-cabbage-fish-soup', category: 'Savory' },
	{ name: 'Pour Over Ginger Scallion Chicken', page: 'savory.html', anchor: 'savory-ginger-scallion-chicken', category: 'Savory' },
	{ name: 'Tomato Egg Korean Somen', page: 'savory.html', anchor: 'savory-tomato-egg-korean-somen', category: 'Savory' },
	{ name: 'Tomato Egg Noodles with Bok Choy', page: 'savory.html', anchor: 'savory-tomato-egg-noodles', category: 'Savory' },
	{ name: 'Scallop Noodles with Apple Salad', page: 'savory.html', anchor: 'savory-scallop-noodles', category: 'Savory' },
	{ name: 'Singaporean Crab', page: 'savory.html', anchor: 'savory-singaporean-crab', category: 'Savory' },
	{ name: 'Potato Tacos', page: 'savory.html', anchor: 'savory-potato-tacos', category: 'Savory' },
	{ name: 'Avocado Toast', page: 'savory.html', anchor: 'savory-avocado-toast', category: 'Savory' },
	{ name: 'Pizza Night', page: 'savory.html', anchor: 'savory-pizza-night', category: 'Savory' },
	{ name: 'Spam Musubi Pyramid', page: 'savory.html', anchor: 'savory-spam-musubi-pyramid', category: 'Savory' },
	{ name: 'Spam Musubi Stacked', page: 'savory.html', anchor: 'savory-spam-musubi-stacked', category: 'Savory' },
	{ name: 'Japchae', page: 'savory.html', anchor: 'savory-japchae', category: 'Savory' },
	{ name: 'Kimchi Butter Udon', page: 'savory.html', anchor: 'savory-kimchi-butter-udon', category: 'Savory' },
	{ name: 'Mapo Tofu', page: 'savory.html', anchor: 'savory-mapo-tofu', category: 'Savory' },
	{ name: 'Sundubu & Bok Choy', page: 'savory.html', anchor: 'savory-sundubu-bok-choy', category: 'Savory' },
	{ name: 'Korean Cold Noodles', page: 'savory.html', anchor: 'savory-korean-cold-noodles', category: 'Savory' },
	{ name: 'Noodles, Dumplings & Banchan', page: 'savory.html', anchor: 'savory-noodles-dumplings-banchan', category: 'Savory' },
	{ name: 'Fried Rice & Bok Choy', page: 'savory.html', anchor: 'savory-fried-rice-bok-choy', category: 'Savory' },
	{ name: 'Fried Rice, Dumplings & Banchan', page: 'savory.html', anchor: 'savory-fried-rice-dumplings', category: 'Savory' },
	{ name: 'Salmon Bowl', page: 'savory.html', anchor: 'savory-salmon-bowl', category: 'Savory' },
	{ name: 'Salmon Bowl with Kimchi', page: 'savory.html', anchor: 'savory-salmon-bowl-kimchi', category: 'Savory' },
	{ name: 'Salmon Bake', page: 'savory.html', anchor: 'savory-salmon-bake', category: 'Savory' },
	{ name: 'Lemon Salmon Pasta', page: 'savory.html', anchor: 'savory-lemon-salmon-pasta', category: 'Savory' },
	{ name: 'Lemon Salmon Pasta with Broccoli', page: 'savory.html', anchor: 'savory-lemon-salmon-pasta-broccoli', category: 'Savory' },
	{ name: 'Chicken Mushroom Alfredo Pasta', page: 'savory.html', anchor: 'savory-chicken-mushroom-alfredo', category: 'Savory' },
	{ name: 'Chili Oil Egg & Bok Choy', page: 'savory.html', anchor: 'savory-chili-oil-egg-bok-choy', category: 'Savory' },
	{ name: 'Beef Enoki Rolls & Chicken Salad', page: 'savory.html', anchor: 'savory-beef-enoki-rolls-chicken-salad', category: 'Savory' },
	{ name: 'Pork Mushroom Rolls & ABC Soup', page: 'savory.html', anchor: 'savory-pork-rolls-abc-soup', category: 'Savory' },
	{ name: 'Stir Fry Potatoes & Lotus Root', page: 'savory.html', anchor: 'savory-stir-fry-potatoes-lotus-root', category: 'Savory' },
	{ name: 'Steamed Fish & ABC Soup', page: 'savory.html', anchor: 'savory-steamed-fish-abc-soup', category: 'Savory' },
	{ name: 'HK Borscht Soup', page: 'savory.html', anchor: 'savory-hk-borscht-soup', category: 'Savory' },
	{ name: 'Tomato Eggs, Curry & Broccoli', page: 'savory.html', anchor: 'savory-tomato-eggs-curry', category: 'Savory' },
	{ name: 'Spring Rolls', page: 'savory.html', anchor: 'savory-spring-rolls', category: 'Savory' },
	{ name: 'Christmas Pizza', page: 'savory.html', anchor: 'savory-christmas-pizza', category: 'Savory' },
	{ name: 'Strawberry Nutella Crepes', page: 'savory.html', anchor: 'savory-strawberry-nutella-crepes', category: 'Savory' },
	{ name: 'Avocado Toast (2)', page: 'savory.html', anchor: 'savory-avocado-toast-2', category: 'Savory' },
	{ name: 'Avocado Toast (3)', page: 'savory.html', anchor: 'savory-avocado-toast-3', category: 'Savory' },

	// Individual macaron designs
	{ name: 'Bees and Unicorn', page: 'macarons.html', anchor: 'macaron-bees-and-unicorn', category: 'Macaron' },
	{ name: 'Eevee and Rowlet', page: 'macarons.html', anchor: 'macaron-eevee-and-rowlet', category: 'Macaron' },
	{ name: 'Winnie and Donald Duck', page: 'macarons.html', anchor: 'macaron-winnie-and-donald', category: 'Macaron' },
	{ name: 'Sully (Monsters Inc.)', page: 'macarons.html', anchor: 'macaron-sully', category: 'Macaron' },
	{ name: 'Kirby', page: 'macarons.html', anchor: 'macaron-kirby', category: 'Macaron' },
	{ name: 'Rainbow', page: 'macarons.html', anchor: 'macaron-rainbow', category: 'Macaron' },
	{ name: 'Gengar', page: 'macarons.html', anchor: 'macaron-gengar', category: 'Macaron' },
	{ name: "Valentine's", page: 'macarons.html', anchor: 'macaron-valentines', category: 'Macaron' },
	{ name: 'Oshawatt', page: 'macarons.html', anchor: 'macaron-oshawatt', category: 'Macaron' },
	{ name: 'Cherry Blossom', page: 'macarons.html', anchor: 'macaron-cherry-blossom', category: 'Macaron' },
	{ name: 'Genshin Impact: Paimon', page: 'macarons.html', anchor: 'macaron-genshin-paimon', category: 'Macaron' },
	{ name: 'Peppa Pig', page: 'macarons.html', anchor: 'macaron-peppa-pig', category: 'Macaron' },
	{ name: 'Reindeer', page: 'macarons.html', anchor: 'macaron-reindeer', category: 'Macaron' },
	{ name: 'Cookie Monster', page: 'macarons.html', anchor: 'macaron-cookie-monster', category: 'Macaron' },
	{ name: 'Pineapple', page: 'macarons.html', anchor: 'macaron-pineapple', category: 'Macaron' },
	{ name: 'Turtles', page: 'macarons.html', anchor: 'macaron-turtles', category: 'Macaron' },
	{ name: 'Corgi', page: 'macarons.html', anchor: 'macaron-corgi', category: 'Macaron' },
	{ name: 'Mallard Ducks', page: 'macarons.html', anchor: 'macaron-mallard-ducks', category: 'Macaron' },
	{ name: 'Vegan Cookies and Cream', page: 'macarons.html', anchor: 'macaron-vegan-cookies-and-cream', category: 'Macaron' },
	{ name: 'DVA', page: 'macarons.html', anchor: 'macaron-dva', category: 'Macaron' },
	{ name: 'Chocolate Chip Cookie', page: 'macarons.html', anchor: 'macaron-chocolate-chip-cookie', category: 'Macaron' },
	{ name: 'Disney Assorted', page: 'macarons.html', anchor: 'macaron-disney-assorted', category: 'Macaron' },
	{ name: 'Pastel Totoro', page: 'macarons.html', anchor: 'macaron-pastel-totoro', category: 'Macaron' },
	{ name: 'Line Friends', page: 'macarons.html', anchor: 'macaron-line-friends', category: 'Macaron' },
	{ name: 'Ice Cream Winnie The Pooh and Piglet', page: 'macarons.html', anchor: 'macaron-ice-cream-winnie-pooh', category: 'Macaron' },
	{ name: 'Ice Cream Line Friends', page: 'macarons.html', anchor: 'macaron-ice-cream-line-friends', category: 'Macaron' },
	{ name: 'Sundae', page: 'macarons.html', anchor: 'macaron-sundae', category: 'Macaron' },
	{ name: 'Smores', page: 'macarons.html', anchor: 'macaron-smores', category: 'Macaron' },
	{ name: 'Ice Cream Macaron Sandwich', page: 'macarons.html', anchor: 'macaron-ice-cream-sandwich', category: 'Macaron' },
	{ name: 'Shamrock', page: 'macarons.html', anchor: 'macaron-shamrock', category: 'Macaron' },
	{ name: 'Shamrock (Cut)', page: 'macarons.html', anchor: 'macaron-shamrock-cut', category: 'Macaron' },

	// Individual cakes (generated from cake alt text)
	{ name: 'Watermelon Cake', page: 'cakes.html', anchor: 'cake-watermelon-cake', category: 'Cake' },
	{ name: 'Stawberry Matcha Cake', page: 'cakes.html', anchor: 'cake-stawberry-matcha-cake', category: 'Cake' },
	{ name: 'Smiski Cake', page: 'cakes.html', anchor: 'cake-smiski-cake', category: 'Cake' },
	{ name: 'Chocolate Cake', page: 'cakes.html', anchor: 'cake-chocolate-cake', category: 'Cake' },
	{ name: 'Jellycat Cake', page: 'cakes.html', anchor: 'cake-jellycat-cake', category: 'Cake' },
	{ name: 'Valentines Jellycat Cake', page: 'cakes.html', anchor: 'cake-valentines-jellycat-cake', category: 'Cake' },
	{ name: 'Carrot Jellycat Cake', page: 'cakes.html', anchor: 'cake-carrot-jellycat-cake', category: 'Cake' },
	{ name: 'Floral Vintage Cake', page: 'cakes.html', anchor: 'cake-floral-vintage-cake', category: 'Cake' },
	{ name: 'Delta Vintage Cake', page: 'cakes.html', anchor: 'cake-delta-vintage-cake', category: 'Cake' },
	{ name: 'Vintage Cake', page: 'cakes.html', anchor: 'cake-vintage-cake', category: 'Cake' },
	{ name: 'Purple Pink Vintage Cake', page: 'cakes.html', anchor: 'cake-purple-pink-vintage-cake', category: 'Cake' },
	{ name: 'Jasmine Mango Cake', page: 'cakes.html', anchor: 'cake-jasmine-mango-cake', category: 'Cake' },
	{ name: 'Tiramisu', page: 'cakes.html', anchor: 'cake-tiramisu', category: 'Cake' },
	{ name: 'Minecraft', page: 'cakes.html', anchor: 'cake-minecraft', category: 'Cake' },
	{ name: 'Pressed Flower Wedding Cake', page: 'cakes.html', anchor: 'cake-pressed-flower-wedding-cake', category: 'Cake' },
	{ name: 'Under The Sea', page: 'cakes.html', anchor: 'cake-under-the-sea', category: 'Cake' },
	{ name: 'Yellow Flowers Cake', page: 'cakes.html', anchor: 'cake-yellow-flowers-cake', category: 'Cake' },
	{ name: 'Floral', page: 'cakes.html', anchor: 'cake-floral', category: 'Cake' },
	{ name: 'Yellow Flowers Cake', page: 'cakes.html', anchor: 'cake-yellow-flowers-cake-2', category: 'Cake' },
	{ name: 'Macaron Cake Pastel Sqaure', page: 'cakes.html', anchor: 'cake-macaron-cake-pastel-sqaure', category: 'Cake' },
	{ name: 'Genshin Cake', page: 'cakes.html', anchor: 'cake-genshin-cake', category: 'Cake' },
	{ name: 'Chocolate Sprinkles', page: 'cakes.html', anchor: 'cake-chocolate-sprinkles', category: 'Cake' },
	{ name: 'Taylor Swift', page: 'cakes.html', anchor: 'cake-taylor-swift', category: 'Cake' },
	{ name: 'Mulan Cake', page: 'cakes.html', anchor: 'cake-mulan-cake', category: 'Cake' },
	{ name: 'KFC', page: 'cakes.html', anchor: 'cake-kfc', category: 'Cake' },
	{ name: 'Butterfly Cake', page: 'cakes.html', anchor: 'cake-butterfly-cake', category: 'Cake' },
	{ name: 'Randy Cake', page: 'cakes.html', anchor: 'cake-randy-cake', category: 'Cake' },
	{ name: 'Strawberry Cake', page: 'cakes.html', anchor: 'cake-strawberry-cake', category: 'Cake' },
	{ name: 'Fruit Cake', page: 'cakes.html', anchor: 'cake-fruit-cake', category: 'Cake' },
	{ name: 'Smores Cake', page: 'cakes.html', anchor: 'cake-smores-cake', category: 'Cake' },
	{ name: 'Cloud Cake', page: 'cakes.html', anchor: 'cake-cloud-cake', category: 'Cake' },
	{ name: 'Pressed Flower Wedding Cake Square', page: 'cakes.html', anchor: 'cake-pressed-flower-wedding-cake-square', category: 'Cake' },
	{ name: 'Bee', page: 'cakes.html', anchor: 'cake-bee', category: 'Cake' },
	{ name: 'Mulan Cake', page: 'cakes.html', anchor: 'cake-mulan-cake-2', category: 'Cake' },
	{ name: 'Pink Rose Macaron Cake', page: 'cakes.html', anchor: 'cake-pink-rose-macaron-cake', category: 'Cake' },
	{ name: 'Yellow Flowers Cake', page: 'cakes.html', anchor: 'cake-yellow-flowers-cake-3', category: 'Cake' },
	{ name: 'Garden Cake', page: 'cakes.html', anchor: 'cake-garden-cake', category: 'Cake' },
	{ name: 'Succulent Cake', page: 'cakes.html', anchor: 'cake-succulent-cake', category: 'Cake' },
	{ name: 'Fruit Cake', page: 'cakes.html', anchor: 'cake-fruit-cake-2', category: 'Cake' },
	{ name: 'Choco Cake Fruit Cake', page: 'cakes.html', anchor: 'cake-choco-cake-fruit-cake', category: 'Cake' },
	{ name: 'Chinese Style Fruit Cake', page: 'cakes.html', anchor: 'cake-chinese-style-fruit-cake', category: 'Cake' },
	{ name: 'Cloud Cake', page: 'cakes.html', anchor: 'cake-cloud-cake-2', category: 'Cake' },
	{ name: 'Dog Box Lunch Cake', page: 'cakes.html', anchor: 'cake-dog-box-lunch-cake', category: 'Cake' },
	{ name: 'Duck Cake', page: 'cakes.html', anchor: 'cake-duck-cake', category: 'Cake' },
	{ name: 'Duck Lunchbox Cake', page: 'cakes.html', anchor: 'cake-duck-lunchbox-cake', category: 'Cake' },
	{ name: 'Rose Lunchbox Cake', page: 'cakes.html', anchor: 'cake-rose-lunchbox-cake', category: 'Cake' },
	{ name: 'Grape Lunchbox', page: 'cakes.html', anchor: 'cake-grape-lunchbox', category: 'Cake' },
	{ name: 'Lunchbox Pastel Pastel Swirl', page: 'cakes.html', anchor: 'cake-lunchbox-pastel-pastel-swirl', category: 'Cake' },
	{ name: 'Flower Lunchbox Cake', page: 'cakes.html', anchor: 'cake-flower-lunchbox-cake', category: 'Cake' },
	{ name: 'Butterfly Cake', page: 'cakes.html', anchor: 'cake-butterfly-cake-2', category: 'Cake' },
	{ name: 'Lunchbox Blueberry', page: 'cakes.html', anchor: 'cake-lunchbox-blueberry', category: 'Cake' },
	{ name: 'Lunchbox Christmas', page: 'cakes.html', anchor: 'cake-lunchbox-christmas', category: 'Cake' },
	{ name: 'Lunchbox Flower', page: 'cakes.html', anchor: 'cake-lunchbox-flower', category: 'Cake' },
	{ name: 'Butterfly Cake Pop', page: 'cakes.html', anchor: 'cake-butterfly-cake-pop', category: 'Cake' },
	{ name: 'Dog Cake Pop', page: 'cakes.html', anchor: 'cake-dog-cake-pop', category: 'Cake' },
	{ name: 'Mermaid Cake Pops', page: 'cakes.html', anchor: 'cake-mermaid-cake-pops', category: 'Cake' },
	{ name: 'Pufferfish (Left)', page: 'cakes.html', anchor: 'cake-pufferfishleft', category: 'Cake' },
	{ name: 'Pufferfish (Mid)', page: 'cakes.html', anchor: 'cake-pufferfishmid', category: 'Cake' },
	{ name: 'Pufferfish (Right)', page: 'cakes.html', anchor: 'cake-pufferfishright', category: 'Cake' },
	{ name: 'Halloween Mickey', page: 'cakes.html', anchor: 'cake-halloween-mickey', category: 'Cake' },
	{ name: 'Jack And Mickey', page: 'cakes.html', anchor: 'cake-jack-and-mickey', category: 'Cake' },
	{ name: 'Jack', page: 'cakes.html', anchor: 'cake-jack', category: 'Cake' },
	{ name: 'Encanto Mini', page: 'cakes.html', anchor: 'cake-encanto-mini', category: 'Cake' },
	{ name: 'Encanto Cactus', page: 'cakes.html', anchor: 'cake-encanto-cactus', category: 'Cake' },
	{ name: 'Encanto Middle', page: 'cakes.html', anchor: 'cake-encanto-middle', category: 'Cake' },
	{ name: 'Giraffe', page: 'cakes.html', anchor: 'cake-giraffe', category: 'Cake' },
	{ name: 'Giraffe And Cactus', page: 'cakes.html', anchor: 'cake-giraffe-and-cactus', category: 'Cake' },
	{ name: 'Zebra', page: 'cakes.html', anchor: 'cake-zebra', category: 'Cake' },
	{ name: 'Choco Stars', page: 'cakes.html', anchor: 'cake-choco-starts', category: 'Cake' },
	{ name: 'Mix', page: 'cakes.html', anchor: 'cake-mix', category: 'Cake' },
	{ name: 'White Choco', page: 'cakes.html', anchor: 'cake-white-choco', category: 'Cake' },
	{ name: 'Better Llama', page: 'cakes.html', anchor: 'cake-better-llama', category: 'Cake' },
	{ name: 'Pikachu', page: 'cakes.html', anchor: 'cake-pikachu', category: 'Cake' },
	{ name: 'Unicorn Cake', page: 'cakes.html', anchor: 'cake-unicorn-cake', category: 'Cake' },
	{ name: 'Strawberry Cover', page: 'cakes.html', anchor: 'cake-strawberry-cover', category: 'Cake' },
	{ name: 'Strawberry Cake', page: 'cakes.html', anchor: 'cake-strawberry-cake-2', category: 'Cake' },
	{ name: 'Strawberry Shortcake', page: 'cakes.html', anchor: 'cake-strawberry-shortcake', category: 'Cake' },
	{ name: "Mother's Day", page: 'cakes.html', anchor: 'cake-mothers-day', category: 'Cake' },
	{ name: 'Chocolate Strawberry', page: 'cakes.html', anchor: 'cake-chocolate-strawberry', category: 'Cake' },
	{ name: 'Ferrero Rocher Cake', page: 'cakes.html', anchor: 'cake-ferrero-rocher-cake', category: 'Cake' },
	{ name: 'Choco Cake', page: 'cakes.html', anchor: 'cake-choco-cake', category: 'Cake' },
	{ name: 'Watermelon Macaron Cake', page: 'cakes.html', anchor: 'cake-watermelon-macaron-cake', category: 'Cake' },
	{ name: 'Strawberry Macarons', page: 'cakes.html', anchor: 'cake-strawberry-macarons', category: 'Cake' },
	{ name: 'Rainbow Macaron', page: 'cakes.html', anchor: 'cake-rainbow-macaron', category: 'Cake' },
	{ name: 'Shopkins Crown', page: 'cakes.html', anchor: 'cake-shopkins-crown', category: 'Cake' },
	{ name: 'Shopkins Ice Cream Cake', page: 'cakes.html', anchor: 'cake-shopkins-ice-cream-cake-new', category: 'Cake' },
	{ name: 'Shopkins Original', page: 'cakes.html', anchor: 'cake-shopkins-orginal', category: 'Cake' },
	{ name: 'Oreo Crepe Cake', page: 'cakes.html', anchor: 'cake-oreo-crepe-cake', category: 'Cake' },
	{ name: 'Ferrero Rocher Cake', page: 'cakes.html', anchor: 'cake-ferrero-rocher-cake-2', category: 'Cake' },
	{ name: 'Mom Birthday Cake', page: 'cakes.html', anchor: 'cake-mom-bday', category: 'Cake' },
	{ name: 'Oreo Crepe Cake', page: 'cakes.html', anchor: 'cake-oreo-crepe-cake-2', category: 'Cake' },
	{ name: 'Mom Birthday Cake', page: 'cakes.html', anchor: 'cake-mom-bday-2', category: 'Cake' },
	{ name: 'Mom Birthday Cake', page: 'cakes.html', anchor: 'cake-mom-bday-3', category: 'Cake' },
	{ name: 'Batman Cake', page: 'cakes.html', anchor: 'cake-batman-cake', category: 'Cake' },
	{ name: 'Promise Of The Neverland Cake', page: 'cakes.html', anchor: 'cake-promise-of-the-neverland-cake', category: 'Cake' },
	{ name: 'Beatles Cake', page: 'cakes.html', anchor: 'cake-beatles-cake', category: 'Cake' },
	{ name: 'Vegan Coconut Mango Cake', page: 'cakes.html', anchor: 'cake-vegan-coconut-mango-cake', category: 'Cake' },
	{ name: 'July Fourth Cake', page: 'cakes.html', anchor: 'cake-july-fourth-cake', category: 'Cake' },
	{ name: 'Garden Cake', page: 'cakes.html', anchor: 'cake-garden-cake-2', category: 'Cake' },
	{ name: 'Vegan Coconut Mango Cake', page: 'cakes.html', anchor: 'cake-vegan-coconut-mango-cake-2', category: 'Cake' },
	{ name: 'July Fourth Cake', page: 'cakes.html', anchor: 'cake-july-fourth-cake-2', category: 'Cake' },
	{ name: 'Garden Cake', page: 'cakes.html', anchor: 'cake-garden-cake-3', category: 'Cake' },
	{ name: 'Minecraft Pig', page: 'cakes.html', anchor: 'cake-minecraft-pig', category: 'Cake' },
	{ name: 'Japanese Cotton Cheese Cake', page: 'cakes.html', anchor: 'cake-japanese-cotton-chese-cake', category: 'Cake' },
	{ name: 'Dad Birthday Cake', page: 'cakes.html', anchor: 'cake-dad-bday', category: 'Cake' },
];